services:
  influxdb:
    image: influxdb:2.8.0@sha256:96410d41a98c02fa5fcddc44cf708e297c8afcf02cd5bb6c620d4ae6a6d12390
    hostname: influxdb
    container_name: influxdb__influxdb
    restart: unless-stopped

    volumes:
      - type: volume
        source: influxdb_conf
        target: /etc/influxdb2

      - type: volume
        source: influxdb_data
        target: /var/lib/influxdb2

    expose:
      - 8086

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 2048m

  cloudflared:
    image: cloudflare/cloudflared:2026.3.0@sha256:6b599ca3e974349ead3286d178da61d291961182ec3fe9c505e1dd02c8ac31b0
    hostname: cloudflared
    container_name: influxdb__cloudflared
    restart: unless-stopped

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      default:

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  influxdb_conf:
    name: influxdb__influxdb_conf

  influxdb_data:
    name: influxdb__influxdb_data

networks:
  default:
    name: influxdb__default
