services:
  influxdb:
    image: influxdb:2.9.1@sha256:270145207873eb426e15a211063532fc6f966f4ffb6edf4114ffac83ac4696eb
    hostname: influxdb
    container_name: influxdb__influxdb
    restart: unless-stopped

    volumes:
      - type: volume
        source: influxdb_conf
        target: /etc/influxdb2

      - type: volume
        source: influxdb_data
        target: /var/lib/influxdb2

    expose:
      - 8086

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 2048m

  cloudflared:
    image: cloudflare/cloudflared:2026.8.1@sha256:d9ff527dc19799e24d3689058161fb01e752a24be1823577bae54c9c2489275f
    hostname: cloudflared
    container_name: influxdb__cloudflared
    restart: unless-stopped

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      default:

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  influxdb_conf:
    name: influxdb__influxdb_conf

  influxdb_data:
    name: influxdb__influxdb_data

networks:
  default:
    name: influxdb__default
