services:
  influxdb:
    image: influxdb:2.9.1@sha256:f75e48af0598e8aec7986e991a848d19a119101a7d563a2e5db1dfaac9c45daa
    hostname: influxdb
    container_name: influxdb__influxdb
    restart: unless-stopped

    volumes:
      - type: volume
        source: influxdb_conf
        target: /etc/influxdb2

      - type: volume
        source: influxdb_data
        target: /var/lib/influxdb2

    expose:
      - 8086

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 2048m

  cloudflared:
    image: cloudflare/cloudflared:2026.9.0@sha256:ff69a2225ad7c6f85ed84fbd5f3087df46202426b2388ec60214098e0adf05e9
    hostname: cloudflared
    container_name: influxdb__cloudflared
    restart: unless-stopped

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      default:

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  influxdb_conf:
    name: influxdb__influxdb_conf

  influxdb_data:
    name: influxdb__influxdb_data

networks:
  default:
    name: influxdb__default
